### ISSUE TITLE
Dynamic GraphQL Schema

### ISSUE THREAD

**Issue by Alfriadox** [rcos/Telescope#58]
There may be some benefits to being able to dynamically generate the GraphQL schema for Juniper. This is not yet currently possible. I will keep an eye on https://github.com/graphql-rust/juniper/issues/7 and other Juniper issues like it.

**Comment by rushsteve1** [comment]
Is this ultimately a desired feature? Alternatively we could run [Hasura](https://hasura.io) over the main RCOS API.

**Comment by Alfriadox** [comment]
We could do that honestly. It's desired if we intend to continue exposing an API as part of telescope but we could separate that concern to another service (temporarily or permanently) and there are definitely valid reasons why we might do that.

**Comment by rushsteve1** [comment]
I would really push Hasura, just because then it's all pulled from Postgres itself.

However the REST vs GraphQL debate is something @Apexal and I went into a lot, and we eventually settled on REST with [PostgREST](https://postgrest.org). We ultimately came to the conclusion that while GraphQL adds a lot of features, PostgREST has similar versions of the most important features and uses a much more well understood and ubiquitous REST interface. This API has to outlast us, so we have to be extremely conservative about our technical decisions.

**Comment by Alfriadox** [comment]
That makes sense. 

It seems like whatever we do, having to manually build out a GraphQL API in rust is not a great option currently. It would take a lot of work and might not be as featureful as as Hasura or as conservative as a REST API. 

With that in mind I'm gonna make a branch removing juniper and GraphQL from this project for now. If we decide later that we do want Telescope to expose an API then we can add them back then.
